bible/urls.py
from django.urls import path

from . import views
app_name = 'bible'

urlpatterns = [
	path('', views.home, name='home'),
	path('chapter/', views.chapter, name="chapter"),
	path('history/', views.history, name="history"),
	path('search/', views.search, name="search"),
	path('history/store/', views.store_history, name="history_store"),
	path('comment/', views.comment, name="comment"),
	path('comment/store/', views.store_comment, name="comment_store"),
	path('comment/update/', views.update_comment, name="comment_update"),
	path('notes/', views.notes, name="notes"),
	path('notes/store/', views.store_notes, name="notes_store"),
	path('comment/delete/', views.delete_comment, name="comment_delete"),
	path('mark/verse/', views.mark_verse, name="mark_verse"),
]

example/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from example import views

urlpatterns = [
	path('', views.loginForm, name='welcome'),
	path('logout/', views.logoutUser, name='logout'),
    path('login/', views.loginForm, name='login'),
	path('authenticate/', views.loginUser, name='authenticate'),
		
    path('home/', include('home.urls')),
    path('journey/', include('journey.urls')),
    path('dictionary/', include('dictionary.urls')),
	path('bible/', include('bible.urls')),
    path('admin/', admin.site.urls),
]

home/urls.py
from django.urls import path

from . import views
app_name = 'home'

urlpatterns = [
	path('', views.home, name='home'),
]

bible/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Bible(models.Model):
	def get_new_testment(self):
		return {
			"Matthew" : 28,
			"Mark" : 16,
			"Luke" : 24,
			"John" : 21,
			"Acts" : 28,
			"Romans" : 16,
			"1 Corinthians" : 16,
			"2 Corinthians" : 13,
			"Galatians" : 6,
			"Ephesians" : 6,
			"Philippians" : 4,
			"Colossians" : 4,
			"1 Thessalonians" : 5,
			"2 Thessalonians" : 3,
			"1 Timothy" : 6,
			"2 Timothy" : 4,
			"Titus" : 3,
			"Philemon" : 1,
			"Hebrews" : 13,
			"James" : 5,
			"1 Peter" : 5,
			"2 Peter" : 3,
			"1 John" : 5,
			"2 John" : 1,
			"3 John" : 1,
			"Jude" : 1,
			"Revelations" : 22
		}

	def get_old_testment(self):
		return {
			"Genesis" : 50,
			"Exodus" : 40,
			"Leviticus" : 27,
			"Numbers" : 36,
			"Deuteronomy" : 34,
			"Joshua" : 24,
			"Judges" : 21,
			"Ruth" : 4,
			"1 Samuel" : 31,
			"2 Samuel" : 24,
			"1 Kings" : 22,
			"2 Kings" : 25,
			"1 Chronicles" : 29,
			"2 Chronicles" : 36,
			"Ezra" : 10,
			"Nehemiah" : 13,
			"Esther" : 10,
			"Job" : 42,
			"Psalms" : 150,
			"Proverbs" : 31,
			"Ecclesiastes" : 12,
			"Songs of Solomon" : 8,
			"Isaiah" : 66,
			"Jeremiah" : 52,
			"Lamentations" : 5,
			"Ezekiel" : 48,
			"Daniel" : 12,
			"Hosea" : 14,
			"Joel" : 3,
			"Amos" : 9,
			"Obadiah" : 1,
			"Jonah" : 4,
			"Micah" : 7,
			"Nahum" : 3,
			"Habakkuk" : 3,
			"Zephaniah" : 3,
			"Haggai" : 2,
			"Zechariah" : 14,
			"Malachi" : 4
		}

	def get_all_bibles(self):
		bibles = self.get_old_testment()
		nt = self.get_new_testment()
		bibles.update(nt)
		return bibles
	def get_all_bibles_list(self):
		b_dict = list(self.get_all_bibles().keys())
		b_list = []
		for i in range(0, len(b_dict)):
			b = (b_dict[i], b_dict[i])
			b_list.append(b)
		return b_list


class BibleHistory(models.Model):
	bible_book		= models.CharField(max_length=50)
	bible_chapter	= models.CharField(max_length=50)
	user			= models.ForeignKey(User, on_delete=models.CASCADE)
	created_at		= models.DateTimeField(auto_now=True)
	updated_at		= models.DateTimeField(auto_now_add=True)

	def save_model(form, request):
		entry = BibleHistory()
		entry.user = request.user
		entry.bible_book = form.cleaned_data['bible_book']
		entry.bible_chapter = form.cleaned_data['bible_chapter']
		entry.save()
		return True


class BibleComment(models.Model):
	verse_ref		= models.CharField(max_length=50)
	comment			= models.TextField()
	user			= models.ForeignKey(User, on_delete=models.CASCADE)
	created_at		= models.DateTimeField(auto_now=True)
	updated_at		= models.DateTimeField(auto_now_add=True)
	
	def save_model(form, request):
		comment = BibleComment()
		comment.user = request.user
		comment.comment = form.cleaned_data['comment']
		comment.verse_ref = form.cleaned_data['verse_ref']
		comment.save()
		return True

	def update_model(form, request):
		try:
			comment = BibleComment.objects.get(id=request.POST["comment_id"])
		except BibleComment.DoesNotExist:
			return True
		comment.comment = form.cleaned_data['comment_edit']
		comment.save()
		return True

	def get_comments(verse_ref, request):
		return BibleComment.objects.filter(
				user= request.user,
				verse_ref = verse_ref
			)

	def delete_comment(verse_ref, request):
		try:
			comment = BibleComment.objects.get(
						id = request.POST["comment_id"]
					);
		except BibleComment.DoesNotExist:
			return True	
		comment.delete()
		return True

class BibleNotebook(models.Model):
	notes			= models.TextField(null=True, blank=True)
	user			= models.ForeignKey(User, on_delete=models.CASCADE)
	created_at		= models.DateTimeField(auto_now=True)
	updated_at		= models.DateTimeField(auto_now_add=True)

	def save_model(form, request):
		try:
			notebook = BibleNotebook.objects.get(user=request.user)
		except BibleNotebook.DoesNotExist:
			notebook = BibleNotebook()
			notebook.user = request.user		
		notebook.notes = form.cleaned_data['notes']
		notebook.save()
		return True

	def get_notes(request):
		return BibleNotebook.objects.get(
				user= request.user
			)

class BibleBookmark(models.Model):
	key		= models.TextField(null=True, blank=True)
	user	= models.ForeignKey(User, on_delete=models.CASCADE)

	def process(request, key):
		try:
			notebook = BibleBookmark.objects.get(user=request.user, key=key)
			notebook.delete()
			return "removed"
		except BibleBookmark.DoesNotExist:
			notebook = BibleBookmark()
			notebook.user = request.user		
			notebook.key = key
			notebook.save()
			return "added"

	def get_bookmarks(request, chapter):
		return BibleBookmark.objects.filter(
				user= request.user,
				key__startswith= chapter
			).values("key")

bible/forms.py
from bible.models import Bible, BibleComment, BibleNotebook
from django import forms

BIBLE_BOOK_CHOICES = Bible().get_all_bibles_list()

class SearchForm(forms.Form):
	search_key = forms.CharField(min_length=3, widget=forms.TextInput(
			attrs={
				"class": "form-control",
				"min": "3",
				"placeholder": "Type search and press enter..."
			}
		))

class RequestForm(forms.Form):
	bible_book = forms.ChoiceField(widget=forms.Select(
			attrs={
				"class": "form-control",	
			}),
		choices = BIBLE_BOOK_CHOICES
	)
	bible_chapter = forms.IntegerField(widget=forms.NumberInput(
			attrs={
				"class": "form-control",
				"value": 1,
				"min":1
			}
		))
	bible_verse = forms.IntegerField(widget=forms.NumberInput(
			attrs={
				"class": "form-control",
				"value": 1,
				"min":1
			}
		))

class BibleNotebookForm(forms.ModelForm):
	class Meta:
		model = BibleNotebook
		fields = [
			'notes'
		]

class BibleCommentForm(forms.ModelForm):
	comment = forms.CharField(min_length=5, widget=forms.Textarea(
			attrs={
				"class": "form-control",
				"min": "5",
				"placeholder": "Type your comment and press enter..."
			}
		))
	class Meta:
		model = BibleComment
		fields = [
			'verse_ref',
			'comment'
		]

class BibleCommentUpdateForm(forms.ModelForm):
	verse_ref_edit = forms.CharField(min_length=5)
	comment_edit = forms.CharField(min_length=5)
	comment_id = forms.IntegerField()
	class Meta:
		model = BibleComment
		fields = [
			'comment_id',
			'comment_edit',
			'verse_ref_edit'
		]

bible/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .forms import SearchForm, RequestForm, BibleNotebookForm, BibleCommentForm, BibleCommentUpdateForm
from .models import Bible, BibleHistory, BibleComment, BibleNotebook, BibleBookmark
from django.http import JsonResponse
from django.template.response import TemplateResponse
from .services import bible_service


# Create your views here.
@login_required
def home(request):
	context = {}

	last_read = BibleHistory.objects.filter(user=request.user).last()
	if(last_read != None):
		current_book = last_read.bible_book
		current_chapter = last_read.bible_chapter
	else:
		current_book = "John"
		current_chapter = 3

	context['ot_books'] = Bible().get_old_testment().keys()
	context['nt_books'] = Bible().get_new_testment().keys()
	context['current_book'] = current_book
	context['current_chapter'] = current_chapter
	context['current_verse_key'] = current_book + " " + str(current_chapter) + ":" + "1"

	context['request_form'] = RequestForm()
	context['search_form'] = SearchForm()
	context['notebook_form'] = BibleNotebookForm()
	context['comment_form'] = BibleCommentForm()
	if "message" in request.session:
		context['message'] = request.session['message']
		del request.session["message"]
	if "error" in request.session:
		context['error'] = request.session['error']
		del request.session["error"]
	return render(request, 'bible_home.html', context)

@login_required
def chapter(request):
	context = {}

	form = RequestForm(request.POST)
	if(form.is_valid()):
		current_book = form.cleaned_data['bible_book']
		current_chapter = form.cleaned_data['bible_chapter']

		chapter_dict = bible_service.get_full_chapter(
								current_book,
								current_chapter
							)
		if(len(chapter_dict)):

			context['chapter'] = TemplateResponse(
								request,
								'includes/bible_chapter.html',
								{
									"chapter": chapter_dict
								}
							).render().rendered_content
			context['result'] = "success"

			chapter_name = current_book + " " + str(current_chapter)
			context['marked_verses'] = list(BibleBookmark.get_bookmarks(request, chapter_name))
			context['current_book'] = current_book
			context['current_chapter'] = current_chapter
			context['chapters_count'] = Bible(). get_all_bibles()[current_book]
			context['verses_count'] = len(chapter_dict.keys())

		else:
			context['result'] = "fail"
			context['html'] = "An error occured and your request could not be handled. Please refresh page and try again"
	else:
		context['result'] = "fail"
		context['html']  = form.errors
	return JsonResponse(context, status=200)



@login_required
def store_history(request):
	context = {}
	form = RequestForm(request.POST)
	if(form.is_valid()):
		BibleHistory.save_model(form, request)
	return JsonResponse({}, status=200)


@login_required
def history(request):
	context = {}

	context['html'] = TemplateResponse(
						request,
						'includes/bible_history.html',
						{
							"history": BibleHistory.objects.filter(user=request.user).order_by("-id")
						}
					).render().rendered_content
	return JsonResponse(context, status=200)

@login_required
def search(request):
	context = {}
	form = SearchForm(request.POST)
	if(form.is_valid()):
		context["result"] = "success"
		context["search_key"] = form.cleaned_data['search_key']
		search_results = bible_service.perform_search(form.cleaned_data['search_key'])
		context["search_results"] = TemplateResponse(
								request,
								'includes/bible_search_results.html',
								{
									"results": search_results,
									"search_key": form.cleaned_data['search_key']
								}
							).render().rendered_content
	else:
		context["result"] = "fail"
		context["errors"] = form.errors
	return JsonResponse(context, status=200)

@login_required
def notes(request):
	context = {}
	context["html"] = BibleNotebook.get_notes(request).notes
	return JsonResponse(context, status=200)

@login_required
def comment(request):
	context = {}
	context["html"] = TemplateResponse(
							request,
							'includes/bible_comments.html',
							{
								"comments": BibleComment.get_comments(request.POST["verse"], request)
							}
						).render().rendered_content
	return JsonResponse(context, status=200)

@login_required
def store_notes(request):
	context = {}
	form = BibleNotebookForm(request.POST)
	if(form.is_valid()):
		context["result"] = "success"
		BibleNotebook.save_model(form, request)
		context["html"] =  BibleNotebook.get_notes(request).notes
	else:
		context["result"] = "fail"
		context["errors"] = form.errors
	return JsonResponse(context, status=200)

@login_required
def store_comment(request):
	context = {}
	form = BibleCommentForm(request.POST)
	if(form.is_valid()):
		context["result"] = "success"
		BibleComment.save_model(form, request)
		comments = BibleComment.get_comments(form.cleaned_data['verse_ref'], request)
		context["html"] = TemplateResponse(
								request,
								'includes/bible_comments.html',
								{
									"comments": comments,
								}
							).render().rendered_content
	else:
		context["result"] = "fail"
		context["errors"] = form.errors
	return JsonResponse(context, status=200)	

@login_required
def update_comment(request):
	context = {}
	form = BibleCommentUpdateForm(request.POST)
	if(form.is_valid()):
		context["result"] = "success"
		BibleComment.update_model(form, request)
		comments = BibleComment.get_comments(form.cleaned_data['verse_ref_edit'], request)
		context["html"] = TemplateResponse(
								request,
								'includes/bible_comments.html',
								{
									"comments": comments,
								}
							).render().rendered_content
	else:
		context["result"] = "fail"
		context["errors"] = form.errors
	return JsonResponse(context, status=200)

@login_required
def delete_comment(request):
	context = {}
	if BibleComment.delete_comment(request.POST["comment_id"], request):
		context["result"] = "success"
		comments = BibleComment.get_comments(request.POST['verse'], request)
		context["html"] = TemplateResponse(
								request,
								'includes/bible_comments.html',
								{
									"comments": comments,
								}
							).render().rendered_content
	else:
		context["result"] = "fail"
		context["error"] = "An error occurred and you comment was not deleted. Please refresh page and try again"

	return JsonResponse(context, status=200)

@login_required
def mark_verse(request):
	context = {}
	result = BibleBookmark.process(request, request.POST['key'])
	if result == "added":
		context["result"] = "success"
		context["action"] = "added"
	elif result == "removed":
		context["result"] = "success"
		context["action"] = "removed"
	else:
		context["result"] = "fail"
		context["error"] = "An error occurred and you verse was not bookmarked. Please refresh page and try again"

	return JsonResponse(context, status=200)

bible/templates/bible_home.html
{% extends "base.html" %}
{% load static %}
{% load dict_value %}


{% block app_name %}bible{% endblock app_name %}
{% block ptitle %}Starr - Bible {% endblock ptitle %}

{% block content %}
	<div class="content">
		<div class="row star-bible-outer">
			<div class="star-bible star-bible-panel col-2 rounded p-0">
				<div class="star-bible-panel-header col-12 p-0">
					<div class="text-white p-1 px-3 rounded-top col-12 bg-primary">Bible Books</div>
				</div>
				<div class="star-bible-panel-body">
					<div class="col-12 star-bible-books">
						<ul class="list">
							{% for book in ot_books %}
								<li {% if book == current_book %} class="active" {% endif %} id='{{ book|cut:" " }}'><a class="text-primary bible-book" onclick="viewBibleBook('{{ book }}')">{{ book }}</a></li>
							{% endfor %}
							<hr>
							{% for book in nt_books %}
								<li {% if book == current_book %} class="active" {% endif %} id='{{ book|cut:" " }}'><a class="text-primary bible-book" onclick="viewBibleBook('{{ book }}')">{{ book }}</a></li>
							{% endfor %}
						</ul>
					</div>
				</div>
			</div>
			<div class="col-10 mx-0 px-0">
				<div class="row mb-1">
					<div class="col-12 pl-5 mr-5">
						<div class="row mr-0">
							<div class="star-bible col-12 bg-white py-1 rounded px-3">
								<div class="sta-body">
									<form class="star-form row" id="bible_form">
										{% csrf_token %}
										<div class="book-form-group">
											<label>Book:</label>
											<select name="bible_book" class="get-bible-input form-control" id="id_bible_book">
												<optgroup label="Old Testament">
													{% for book in ot_books %}
															<option {% if current_book == book %} selected {% endif %} value="{{ book }}">{{ book }}</option>
													{% endfor %}
												</optgroup>
												<optgroup label="New Testament">
													{% for book in nt_books %}
															<option {% if current_book == book %} selected {% endif %} value="{{ book }}">{{ book }}</option>
													{% endfor %}
												</optgroup>
											</select>
										</div>
										<div class="chapter-form-group">
											<label>Chapter:</label>
											<input type="number" name="bible_chapter" class="get-bible-input form-control" value="{{ current_chapter }}" min="1" max="{{ chapters_count }}" required="" id="id_bible_chapter">
										</div>
										<div class="verse-form-group">
											<label>Verse:</label>
											<input type="number" name="bible_verse" class="form-control" value="1" min="1" max="{{ verses_count }}" required="" id="id_bible_verse">
										</div>
									</form>
									<form class="star-form row" id="bible_search_form">
										<div class="search-form-group">
											{{ search_form.search_key }}
											<input type="submit" value="Search" name="Search" class="btn btn-primary btn-sm">
										</div>
									</form>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-7 pl-5 pr-4">
						<div class="row">
							<div class="star-bible col-12 bg-white px-3 pt-1 rounded">
								<div class="sta-body">
									<a href="#" class="btn btn-secondary btn-xs active">ESV</a>
									<a href="#" class="btn btn-secondary btn-xs">NIV</a>
									<a href="#" class="btn btn-secondary btn-xs">KJV</a>
									<a href="#" class="btn btn-secondary btn-xs">NKJV</a>
								</div><hr class="my-2">
							</div>
							<div class="star-bible col-12 bg-white px-3 rounded">
								<div class="star-bible-contents mb-3">
									<!-- {% include "includes/bible_chapter.html" %} -->
								</div>
							</div>
						</div>
					</div>
					<div class="col-5">
						<div class="row pr-3">
							<div class="star-bible col-12 bg-white px-3 pt-1 rounded">
								<div class="sta-body">
									<a href="#" onclick="utilTab('comments')" id="view_comments" class="bible-util-btn btn btn-secondary btn-xs active">Comments</a>
									<a href="#" onclick="viewNotes()" id="view_notebook" class="bible-util-btn btn btn-secondary btn-xs">Notebook</a>
									<a href="#" onclick="viewHistory()" id="view_history" class="bible-util-btn btn btn-secondary btn-xs">History</a>
									<a href="#" onclick="utilTab('search')" id="view_search" class="bible-util-btn btn btn-secondary btn-xs d-none">Search Results</a>
								</div><hr class="my-2">
							</div>
							<div class="star-bible col-12 bg-white px-3 rounded">
								<div class="star-bible-utils mb-3">
									<div id="star_bible_comments" class="bible-util-tab">
										<b>Your Comments</b>
										<ul class="list mb-2">
										</ul>
										<div class="bible-comment-form">
											<form id="bible_comment_form">
												{{ comment_form.comment }}
												<input type="hidden" name="verse_ref" id="id_current_verse_key" value="{{ current_verse_key }}">
												<input type="submit" name="Submit" value="Submit" class="btn btn-xs btn-primary float-right">
											</form>
										</div>
									</div>
									<div id="star_bible_notebook" class="bible-util-tab d-none">
										<div class="bible-notebook-form">
											<form id="bible_notebook_form">
												<textarea id="notebook" name="notes"></textarea>
												<input type="submit" name="Save" value="Save" class="btn btn-xs btn-primary float-right">
										</div>
									</div>
									<div id="star_bible_history" class="bible-util-tab d-none">
										
									</div>
									<div id="star_bible_search" class="bible-util-tab d-none">
										<div class="text-center col-12 mt-3 font-weight-bold">Searching... <i></i></div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	{% include 'includes/messages.html' %}
	{% include "includes/delete_comment.html" %}
	{% include "includes/edit_comment.html" %}
{% endblock content %}

{% block lower_static %}
	<script src="{% static 'js/ckeditor.js' %}"></script>
	<script type="text/javascript">
		let editor;
		ClassicEditor
		    .create( document.querySelector( '#notebook' ) )
		    .then( newEditor => {
		        editor = newEditor;
		    } )
		    .catch( error => {
		        console.error( error );
		    } );			
	</script>
	<script type="text/javascript" src="{% static 'js/bible.js' %}"></script>
{% endblock lower_static %}