example/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from example import views

urlpatterns = [
	path('', views.loginForm, name='welcome'),
	path('logout/', views.logoutUser, name='logout'),
    path('login/', views.loginForm, name='login'),
	path('authenticate/', views.loginUser, name='authenticate'),
		
    path('home/', include('home.urls')),
    path('journey/', include('journey.urls')),
    path('dictionary/', include('dictionary.urls')),
	path('bible/', include('bible.urls')),
    path('admin/', admin.site.urls),
]

home/urls.py
from django.urls import path

from . import views
app_name = 'home'

urlpatterns = [
	path('', views.home, name='home'),
]

journey/urls.py
from django.urls import path

from . import views
app_name = 'journey'

urlpatterns = [
	path('', views.home, name='home'),
	path('story/', views.story, name="story"),
	path('story/update/<int:id>', views.update_story, name="update_story"),
	path('story/delete/<int:id>', views.delete_story, name="delete_story"),
]

journey/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Journey(models.Model):
	def __str__(self):
		return self.story

	story			= models.TextField();
	user			= models.ForeignKey(User, on_delete=models.CASCADE)
	created_at		= models.DateTimeField(auto_now=True)
	updated_at		= models.DateTimeField(auto_now_add=True)
	
	def save_model(form, request):
		story = Journey()
		story.user = request.user
		story.story = form.cleaned_data['story']
		story.save()
		return True

	def update_model(form, request, id):
		try:
			story = Journey.objects.get(id = id, user=request.user)
		except Journey.DoesNotExist:
			return True		
		story.story = form.cleaned_data['story']
		story.save()
		return True

	def delete_model(request, id):
		try:
			story = Journey.objects.get(id = id, user=request.user)
		except Journey.DoesNotExist:
			return True		
		story.delete()
		return True

journey/forms.py
from journey.models import Journey
from django import forms

class StoryForm(forms.Form):
	story = forms.CharField()

journey/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import StoryForm
from .models import Journey
from django.http import JsonResponse
from django.template.response import TemplateResponse


# Create your views here.
@login_required
def home(request, *args, **kwargs):
	context = {}
	if "message" in request.session:
		context['message'] = request.session['message']
		del request.session["message"]
	if "error" in request.session:
		context['error'] = request.session['error']
		del request.session["error"]

	queryset = Journey.objects.filter(user=request.user).order_by("-id")
	context['objects'] = queryset
	context['form'] = StoryForm()
	return render(request, 'journey_home.html', context)

@login_required
def story(request):
	form = StoryForm(request.POST)
	context = {}
	if form.is_valid():
		if(Journey.save_model(form, request)):
			context['result']  = "success"
			context['html'] = "Your story has been kept so secretly"

			context['new_story'] = TemplateResponse(
									request,
									'includes/story.html',
									{'object': Journey.objects.filter(
													user=request.user
												).order_by("-id")[:1].get()}
								).render().rendered_content
			return JsonResponse(context, status=200)
		else:
			context['result']  = "fail"
			context['html'] = "Ohhh I am sorry, an error occured, I could not save your story. Please try again."
	else:
		context['result']  = "fail"
		context['html'] = form.errors
	return JsonResponse(context, status=200)

@login_required
def update_story(request, id):
	form = StoryForm(request.POST)
	context = {}
	if form.is_valid():
		if(Journey.update_model(form, request, id)):
			context['result']  = "success"
			context['html'] = "Your story has been updated"
			context['your_story'] = TemplateResponse(
									request,
									'includes/inner_story.html',
									{'object': Journey.objects.get(pk=id)}
								).render().rendered_content
			return JsonResponse(context, status=200)
		else:
			context['result']  = "fail"
			context['html'] = "Ohhh I am sorry, an error occured, I could not save your story. Please try again."
	else:
		context['result']  = "fail"
		context['html'] = form.errors
	return JsonResponse(context, status=200)

@login_required
def delete_story(request, id):
	context = {}
	if(Journey.delete_model(request, id)):
		context['result']  = "success"
		request.session['message'] = "A story was successfully deleted."
	else:
		context['result']  = "fail"
		request.session['error'] = "A story was successfully deleted."

	return redirect("journey:home")

journey/templates/journey_home.html
{% extends "base.html" %}
{% load static %}

{% block app_name %}journey{% endblock app_name %}
{% block ptitle %}Starr - Journey {% endblock ptitle %}

{% block content %}
	<div class="content">
		<div class="row star-journey-outer">
			<div class="star-journey col-6 offset-3 bg-white p-3 rounded">
				<div class="star-head">
					<p class="mb-4 px-1">
						Hey {{ request.user }}! How are you doing today?
					</p>
				</div>
				<div class="star-body">
					<form class="star-form mb-5" id="story_form" method="POST" action="{% url 'journey:home' %}">
						{% csrf_token %}
						{# {{ form.user }} #}
						<div class="form-group">
							<textarea name="story" cols="40" rows="10" class="form-control" placeholder="Tell me something about today, like what have you been up to..." id="id_story"></textarea>
						</div>
						<div class="form-group row">
							<div class="star-journey-sucess col-10"></div>
							<div class="col-2">					
								<input type="submit" name="Submit" class="btn btn-primary btn-sm">
							</div>
						</div>
					</form>
					
					<div class="journey-story-head">
						<h5 class="h5">Stories.</h5>
					</div><hr>
					<div class="journey-stories">
						{% for object in objects %}
							{% include 'includes/story.html' %}
						{% empty %}
							<div class="journey-story">
								<p>Remember, you haven't told me any stories yet.</p>
							</div>
						{% endfor %}
					</div>
				</div>
			</div>
		</div>
	</div>

	{% include 'includes/messages.html' %}
	{% include 'includes/edit_story.html' %}
	{% include 'includes/delete_story.html' %}
{% endblock content %}

{% block lower_static %}
	<script src="{% static 'js/ckeditor.js' %}"></script>
	<script type="text/javascript">
		let editor;
		ClassicEditor
		    .create( document.querySelector( '#id_story' ) )
		    .then( newEditor => {
		        editor = newEditor;
		    } )
		    .catch( error => {
		        console.error( error );
		    } );			
	</script>
	<script type="text/javascript" src="{% static 'js/journey.js' %}"></script>
{% endblock lower_static %}