bible/urls.py
from django.urls import path

from . import views
app_name = 'bible'

urlpatterns = [
	path('', views.home, name='home'),
	path('chapter/', views.chapter, name="chapter"),
	path('history/', views.history, name="history"),
	path('search/', views.search, name="search"),
	path('history/store/', views.store_history, name="history_store"),
	path('comment/', views.comment, name="comment"),
	path('comment/store/', views.store_comment, name="comment_store"),
	path('comment/update/', views.update_comment, name="comment_update"),
	path('notes/', views.notes, name="notes"),
	path('notes/store/', views.store_notes, name="notes_store"),
	path('comment/delete/', views.delete_comment, name="comment_delete"),
	path('mark/verse/', views.mark_verse, name="mark_verse"),
]

dictionary/urls.py
from django.urls import path

from . import views
app_name = 'dictionary'

urlpatterns = [
	path('', views.home, name='home'),
	path('search/', views.search_word, name="search"),
]

example/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from example import views

urlpatterns = [
	path('', views.loginForm, name='welcome'),
	path('logout/', views.logoutUser, name='logout'),
    path('login/', views.loginForm, name='login'),
	path('authenticate/', views.loginUser, name='authenticate'),
		
    path('home/', include('home.urls')),
    path('journey/', include('journey.urls')),
    path('dictionary/', include('dictionary.urls')),
	path('bible/', include('bible.urls')),
    path('admin/', admin.site.urls),
]

home/urls.py
from django.urls import path

from . import views
app_name = 'home'

urlpatterns = [
	path('', views.home, name='home'),
]

journey/urls.py
from django.urls import path

from . import views
app_name = 'journey'

urlpatterns = [
	path('', views.home, name='home'),
	path('story/', views.story, name="story"),
	path('story/update/<int:id>', views.update_story, name="update_story"),
	path('story/delete/<int:id>', views.delete_story, name="delete_story"),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required
def home(request):
	return render(request, 'home.html', {})

templates/base.html
<!DOCTYPE html>
<html>
<head>
	{% load static %}
	{% include "includes/head.html" %}
	<title>{% block ptitle %} {% endblock ptitle %}</title>
	{% block upper_static %} {% endblock upper_static %}
</head>
<body>
	<header class="px-5">
		<div class="logo dropdown">
			<a href=""><span>&lt/starr:{% block app_name %} {% endblock app_name %}&gt</span></a>
			<a href="" class="text-white ml-2" data-toggle="dropdown"><i class="iconmoon icon-caret-square-o-down"></i></a>
			  <ul class="dropdown-menu p-0">
			    <li><a href="{% url 'journey:home' %}">&ltstarr:journey&gt</a></li>
			    <li><a href="{% url 'dictionary:home' %}">&ltstarr:dictionary&gt</a></li>
			    <li><a href="{% url 'bible:home' %}">&ltstarr:bible&gt</a></li>
			    <li><a href="#">&ltstarr:todo&gt</a></li>
			  </ul>
		</div>
		<div class="links text-right text-white">
			<i class="icon-user"></i><span class="px-1 username">{{ request.user|title }}:</span>
			<a href="{% url 'logout' %}" class="text-white">Account</a><span class="px-1">/</span>
			<a href="{% url 'logout' %}" class="text-white">Logout</a>
		</div>
	</header>
	{% block content %} {% endblock content %}

	{% include "includes/scripts.html" %}
	{% block lower_static %} {% endblock lower_static %}
</body>
</html>

templates/home.html
{% extends "base.html" %}
{% load static %}

{% block app_name %}home{% endblock app_name %}
{% block ptitle %}Starr - Home {% endblock ptitle %}

{% block content %}
	<div class="content">
		<div class="row">
			<div class="col-8 offset-2">
				<div class="row">
					<div id="journey" class="col-3 star-product">
						<div class="star-product-head">
							<span>&ltstarr:journey/&gt</span>
						</div>
						<div class="star-product-body">
							<i class="iconmoon icon-road"></i>
						</div>
					</div>
					<div id="dictionary" class="col-3 star-product">
						<div class="star-product-head">
							<span>&ltstarr:dictionary/&gt</span>
						</div>
						<div class="star-product-body">
							<i class="iconmoon icon-search"></i>
						</div>
					</div>
					<div id="bible" class="col-3 star-product">
						<div class="star-product-head">
							<span>&ltstarr:bible/&gt</span>
						</div>
						<div class="star-product-body">
							<i class="iconmoon icon-book"></i>
						</div>
					</div>
					<div id="todo" class="col-3 star-product">
						<div class="star-product-head">
							<span>&ltstarr:todo/&gt</span>
						</div>
						<div class="star-product-body">
							<i class="iconmoon icon-today"></i>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

{% endblock content %}

{% block lower_static %}
	<script type="text/javascript" src="{% static 'js/scripts.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
	<script type="text/javascript">
		$(".star-product-body").click(function(){
		  location.href = "/" + $(this).parent().attr('id');
		});
	</script>	
{% endblock lower_static %}

templates/login.html
<!DOCTYPE html>
<html>
<head>
	{% load static %}
	<title>Starr Login</title>
	<script type="text/javascript" src="{% static 'js/jquery-3.2.1.js' %}"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'css/public.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/nav.css' %}">
</head>
<body>
	<header class="px-5">
		<div class="logo">
			<span>&lt/starr&gt</span>
		</div>
		<div class="links text-right">
			<b class="text-white">A light in the darkness</b>
		</div>
	</header>
	<div class="content">
		<div class="row pt-5 mx-5 px-5">
			<div class="col-4 offset-4 mt-5 p-0 bg-white">
				<div class="form-header p-3 rounded-top mb-2">
					<span class="text-white h6">Login Form</span>
				</div>
				<div class="px-3">
					<form class="form" method="POST" action="{% url 'authenticate' %}">
						{% csrf_token %}
						{% if message is not None %}
							<div class="alert alert-primary bg-white text-primary font-weight-bold border-primary alert-dismissible">
						  	<a href="#" class="close p-2" data-dismiss="alert" aria-label="close">&times;</a>
								{{ message }}
							</div>
						{% endif %}
						{% if error is not None %}
							<div class="alert alert-danger bg-white text-danger font-weight-bold border-danger  alert-dismissible">
						  	<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
								{{ error }}
							</div>
						{% endif %}						
						<div class="form-group">
							<label class="control-label">Username:</label>
							<input type="text" name="username" class="form-control">
						</div>
						<div class="form-group">
							<label class="control-label">Password:</label>
							<input type="password" name="password" class="form-control">
						</div>
						<div class="form-group text-right">
							<input type="submit" name="submit" class="btn btn-primary btn-sm">
						</div>						
					</form>
				</div>
			</div>
		</div>
	</div>
	<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>